# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/be37cb54-a32f-4683-9c65-b7fb0bcbf483";
    fsType = "ext2";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/a6e13434-0508-4727-b371-4934e1d3dba7";
    fsType = "btrfs";
    options = [ "compress=zstd:6" "noatime" ];
  };

  # fileSystems."/tmp" = {
  #   device = "tmpfs";
  #   fsType = "tmpfs";
  # };

  zramSwap = {
    enable = true;
    memoryPercent = 50;
    algorithm = "zstd";
  };

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
