# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FF8B-5F2E";
    fsType = "vfat";
  };

  boot.initrd.luks.devices."root" = {
    device = "/dev/disk/by-uuid/956ade2b-027b-48e2-82f7-b9591186d7e2";
    allowDiscards = true;
    fallbackToPassword = true;
    keyFile = "/dev/disk/by-partuuid/a40374be-2443-4c01-ae9d-159f4906d127";
    keyFileSize = 1024;
  };
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/2d65633a-a5d4-48b9-aef8-e26fef389f26";
    fsType = "btrfs";
  };

  boot.initrd.luks.devices."store" = {
    device = "/dev/disk/by-uuid/5d6841d3-aa0c-4cbf-b191-63c8b5253bd6";
    fallbackToPassword = true;
    keyFile = "/dev/disk/by-partuuid/a40374be-2443-4c01-ae9d-159f4906d127";
    keyFileSize = 1024;
  };
  fileSystems."/srv/store" = {
    device = "/dev/disk/by-uuid/e40f321c-c915-41d3-8f56-5d1c56155b84";
    fsType = "btrfs";
  };

  swapDevices = [ ];
}
