# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "nvme"
    "sd_mod"
    "uas"
    "usb_storage"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/EAE0-FEEB";
    fsType = "vfat";
  };


  boot.initrd.luks.devices."root" = {
    device = "/dev/disk/by-uuid/a4661cb5-1a2d-4ca7-a32c-4c1b6e499d9c";
    keyFile = "/dev/disk/by-partuuid/76c03551-6f37-4a52-a112-7f4411716998";
    allowDiscards = true;
    fallbackToPassword = true;
  };

  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [ "compress=zstd:6" "noatime" ];
  };


  boot.initrd.luks.devices."archive-1" = {
    device = "/dev/disk/by-uuid/7da40a3e-cad4-42b9-bca6-18d30aecbec6";
    keyFile = "/dev/disk/by-partuuid/76c03551-6f37-4a52-a112-7f4411716998";
    allowDiscards = true;
    fallbackToPassword = true;
  };

  boot.initrd.luks.devices."archive-2" = {
    device = "/dev/disk/by-uuid/21458655-7fb6-468e-aab6-b8111b8566f4";
    keyFile = "/dev/disk/by-partuuid/76c03551-6f37-4a52-a112-7f4411716998";
    allowDiscards = true;
    fallbackToPassword = true;
  };

  boot.initrd.luks.devices."archive-3" = {
    device = "/dev/disk/by-uuid/1ec72268-78de-4c56-98d4-3fd7185aaa5c";
    keyFile = "/dev/disk/by-partuuid/76c03551-6f37-4a52-a112-7f4411716998";
    allowDiscards = true;
    fallbackToPassword = true;
  };

  fileSystems."/srv/archive" = {
    device = "/dev/mapper/archive-1";
    fsType = "btrfs";
    options = [ "compress=zstd:9" "noatime" ];
  };


  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/9fca8820-016f-f243-a75d-3eb509ee6966";
      discardPolicy = "both";
      randomEncryption.enable = true;
    }
  ];
}
