# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "r8169"
    "sd_mod"
    "usbhid"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [
    "nls_cp437"
    "nls_iso8859-1"
    "r8169"
    "usbhid"
    "vfat"
  ];
  boot.initrd.network.enable = true;

  boot.initrd.luks.gpgSupport = true;

  boot.initrd.luks.devices."root" = {
    device = "/dev/disk/by-uuid/47a2fa95-920c-4167-9243-f68375909ccd";
    fallbackToPassword = true;
    allowDiscards = true;
    gpgCard = {
      encryptedPass = ./pass.gpg;
      publicKey = ./public-keys.pgp.asc;
    };
  };

  boot.initrd.luks.devices."home" = {
    device = "/dev/disk/by-uuid/c766b927-db66-48eb-8e66-2e30c63655a8";
    fallbackToPassword = true;
    allowDiscards = true;
    gpgCard = {
      encryptedPass = ./pass.gpg;
      publicKey = ./public-keys.pgp.asc;
    };
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/ADC5-4424";
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0d12b8e1-8d19-4543-8b45-b18628692e8b";
    fsType = "btrfs";
    options = [ "compress=zstd" "noatime" ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/05d69054-3fd5-4708-9c32-344309331c48";
    fsType = "btrfs";
    options = [ "compress=zstd" "noatime" ];
  };

  swapDevices = [{
    device = "/dev/disk/by-partuuid/d1b801c9-68bb-124b-b26d-6ada01bee825";
    randomEncryption.enable = true;
  }];

  nix.maxJobs = lib.mkDefault 4;
}
