# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [
    "ahci"
    "sd_mod"
    "usb_storage"
    "usbhid"
    "xhci_pci"
  ];
  boot.initrd.kernelModules = [ ];
  boot.initrd.network.enable = true;

  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."root" = {
    device = "/dev/disk/by-uuid/19ce3347-91dc-46db-98a8-76905e42b782";
    allowDiscards = true;
    fallbackToPassword = true;
    keyFile = "/dev/disk/by-partuuid/b0457298-68bd-4e85-9420-542edcea9811";
  };

  boot.initrd.luks.devices."root-2" = {
    device = "/dev/disk/by-uuid/28349042-36bd-4716-a349-aee3978aaaf1";
    allowDiscards = true;
    fallbackToPassword = true;
    keyFile = "/dev/disk/by-partuuid/b0457298-68bd-4e85-9420-542edcea9811";
  };

  boot.initrd.luks.devices."store" = {
    device = "/dev/disk/by-uuid/47a2fa95-920c-4167-9243-f68375909ccd";
    allowDiscards = true;
    fallbackToPassword = true;
    keyFile = "/dev/disk/by-partuuid/b0457298-68bd-4e85-9420-542edcea9811";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/3028-FA3F";
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [ "compress=zstd:9" "noatime" ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/store";
    fsType = "btrfs";
    options = [ "compress=zstd:6" "noatime" "subvol=home" ];
  };

  fileSystems."/srv" = {
    device = "/dev/mapper/store";
    fsType = "btrfs";
    options = [ "compress=zstd:9" "noatime" "subvol=srv" ];
  };

  swapDevices = [
    {
      device = "/dev/disk/by-partuuid/f0d2575a-b8ba-904b-a6fa-3737f07a0d08";
      randomEncryption.enable = true;
      discardPolicy = "both";
    }
    {
      device = "/dev/disk/by-partuuid/361950b3-c225-754c-9888-3f17c65c1ebc";
      randomEncryption.enable = true;
      discardPolicy = "both";
    }
  ];

  nix.maxJobs = lib.mkDefault 4;
}
