# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  boot.initrd.availableKernelModules = [ "usbhid" "usb_storage" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" = {
    device = "/dev/mmcblk0p1";
    fsType = "vfat";
  };

  boot.initrd.luks.devices."root" = {
    device = "/dev/disk/by-uuid/8f3a6f64-c49d-4de8-90ec-1d49d5c45055";
    fallbackToPassword = true;
    allowDiscards = true;
    keyFile = "/dev/disk/by-partuuid/4627f9ec-03";
    keyFileSize = 32;
  };
  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [ "noatime" ];
  };

  fileSystems."/tmp" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
}
