# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  boot.initrd.availableKernelModules =
    [ "xhci_pci" "ahci" "usbhid" "usb_storage" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/517A-4191";
    fsType = "vfat";
  };

  boot.initrd.luks.devices."root" = {
    device = "/dev/disk/by-uuid/776cf87f-9996-4610-a56e-1c63e3738af7";
    fallbackToPassword = true;
    allowDiscards = true;
  };
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/6580a7d2-b8f3-46c0-933d-01b94cafedc6";
    fsType = "btrfs";
    options = [ "noatime" ];
  };

  fileSystems."/tmp" = {
    device = "tmpfs";
    fsType = "tmpfs";
  };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
}
