# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices."root" = {
    device = "/dev/disk/by-uuid/956ade2b-027b-48e2-82f7-b9591186d7e2";
    allowDiscards = true;
    fallbackToPassword = true;
    keyFile = "/dev/disk/by-partlabel/prophet";
  };

  boot.initrd.luks.devices."swap" = {
    device = "/dev/disk/by-uuid/daa59ae4-2785-4be6-b2b1-60176e6b9987";
    allowDiscards = true;
    fallbackToPassword = true;
    keyFile = "/dev/disk/by-partlabel/prophet";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/FF8B-5F2E";
    fsType = "vfat";
  };

  fileSystems."/" = {
    device = "/dev/mapper/root";
    fsType = "btrfs";
    options = [ "compress=zstd:6" "noatime" ];
  };

  # fileSystems."/tmp" = {
  #   device = "tmpfs";
  #   fsType = "tmpfs";
  # };

  swapDevices = [{ device = "/dev/mapper/swap"; discardPolicy = "both"; }];
}
